import React from "react";
import Card from "./Card";
import { LuWandSparkles } from "react-icons/lu";
import { LuClapperboard } from "react-icons/lu";
import { RiVoiceAiFill } from "react-icons/ri";
import { MdOutlineQuiz } from "react-icons/md";

function Gallery() {
  return (
    <div>
      <p className="section-label">What's under the hood</p>
      <div className="gallery">
        <Card
          icon={<LuWandSparkles />}
          title="Three AI models"
          text="GPT-4o scripts it. Gemini refines the language. Gemini writes the quiz. Each model does what it's best at."
        />
        <Card
          icon={<LuClapperboard />}
          title="Frame-by-frame animation"
          text="p5.js sketches render in a headless browser — every frame is drawn fresh for the topic, not pulled from a library."
        />
        <Card
          icon={<RiVoiceAiFill />}
          title="Actual narration"
          text="OpenAI TTS reads every segment, timed to the animation. Sounds like a teacher explaining, not text-to-speech."
        />
        <Card
          icon={<MdOutlineQuiz />}
          title="Quiz included"
          text="10 topic-specific questions after every video. Generated by Gemini, not a generic template. Retention built in."
        />
      </div>
    </div>
  );
}

export default Gallery;
